### ISSUE TITLE
Trying to run MatLab code

### ISSUE THREAD

**Issue by benjiebob** [dut09/arap#1]
Hi dut09,

Just wondering if you could help me get the MatLab code up and running. Firstly, I'm having trouble locating the square_21_spikes model. I think on your machine, it may be under the following directory: MODEL_NAME=/home/taodu/research/arap/model/square_21_spikes

The code makes reference to these items in a few places, e.g. as below:

[V, F] = readoff('../model/square_21_spikes.off');
id = readdmat('../model/square_21_spikes-selection.dmat');
C = readdmat('../model/square_21_spikes.dmat');

From here, I'll try configuring Eigen3 and libigl before running the build.sh script. 

Thanks,

Benjamin Biggs

**Comment by dut09** [comment]
Hi Benjamin,

You can find square_21_spikes here:
http://igl.ethz.ch/projects/ARAP/Meshes_ARAP_SorkineAlexa_2007.zip

Please let me know if you need more help.

Thanks,
Tao

**Comment by benjiebob** [comment]
Hi Tao,

Thanks for supplying this file. I've managed to successfully run cmake but am now having trouble with the make command.

Error is as follows -- could this be due to a change in the libigl API?

[  9%] Building CXX object demo/CMakeFiles/demo_bin.dir/main.cc.o
In file included from /scratch/bjb56/download/arap/demo/main.cc:5:0:
/scratch/bjb56/download/arap/demo/arapbenchmarksolver.h:6:29: fatal error: igl/svd3x3/arap.h: No such file or directory
compilation terminated.
demo/CMakeFiles/demo_bin.dir/build.make:65: recipe for target 'demo/CMakeFiles/demo_bin.dir/main.cc.o' failed
make[2]: *** [demo/CMakeFiles/demo_bin.dir/main.cc.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'demo/CMakeFiles/demo_bin.dir/all' failed
make[1]: *** [demo/CMakeFiles/demo_bin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Would be grateful for any tips :)

Thanks

Ben

**Comment by benjiebob** [comment]
Thanks for this :)
