### ISSUE TITLE
Incorrect API calls to libigl (probably since a version update)

### ISSUE THREAD

**Issue by benjiebob** [dut09/arap#2]
Hi Tao,

Thanks for supplying this file. I've managed to successfully run cmake but am now having trouble with the make command.

Error is as follows -- probably due to a change in the libigl API?

[  9%] Building CXX object demo/CMakeFiles/demo_bin.dir/main.cc.o
In file included from /scratch/bjb56/download/arap/demo/main.cc:5:0:
/scratch/bjb56/download/arap/demo/arapbenchmarksolver.h:6:29: fatal error: igl/svd3x3/arap.h: No such file or directory
compilation terminated.
demo/CMakeFiles/demo_bin.dir/build.make:65: recipe for target 'demo/CMakeFiles/demo_bin.dir/main.cc.o' failed
make[2]: *** [demo/CMakeFiles/demo_bin.dir/main.cc.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'demo/CMakeFiles/demo_bin.dir/all' failed
make[1]: *** [demo/CMakeFiles/demo_bin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Thanks

Ben

**Comment by benjiebob** [comment]
...
OK, I've gone through and fixed these errors. There were a few places to relace igl/svd3x3/<x> with just igl/<x>. I also found that I needed to change references to namespace igl::Viewer& viewer with igl::viewer:Viewer&.

If you'd like me to commit these changes, let me know.

**Comment by dut09** [comment]
Thanks! That'll be very helpful. If you can create a pull request then I'd be happy to take a look and merge.

**Comment by GloriaBian** [comment]
Could you tell me how do you choose the handles and fixed points when you do the laplacian deformation? Thanks a lot!
